version: "3"

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
volumes:
  postgres:
    driver: local
